[package]
name = "isometric_fighting"
version = "0.1.28"
authors = ["Fedor Rusak <node@fedor-rusak.ru>"]
edition = "2018"
license = "MIT"

[dependencies]
ggez = { git = "https://github.com/fedor-rusak/ggez", rev = "4fdde1c" }
rand = "0.7"

[profile.dev]
opt-level=2